### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/HumansOfGitHub#1]
Open project in Xcode and run app in iPhone simulator or device. Take screenshots for each screen and put them in a "screenshots" folder and update in README.md

**Comment by minibhati93** [comment]
I want to help. Can I work on this?

**Comment by raj-subhankar** [comment]
@minibhati93 sure, go ahead

**Comment by abdulajet** [comment]
I'll give this a try :)
