### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/HumansOfGitHub#4]
Add a basic CONTRIBUTING.md similar to https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by Nitish18** [comment]
Hi @raj-subhankar ,
can I work on this issue ?
I can even contribute to the Android version of the App , if there are some open issues in it.
Thanks.

**Comment by raj-subhankar** [comment]
@Nitish18 hi, sure go ahead with adding the CONTRIBUTING.md file. Do you want to create the android version of this app? Because I have not started work on that.

**Comment by Nitish18** [comment]
@raj-subhankar ,yeah I would love to work on the Android version.First, I'll finish the contribute.md part.

**Comment by raj-subhankar** [comment]
@Nitish18 cool, let me know how you decide to proceed

**Comment by raj-subhankar** [comment]
@Nitish18 also @gtarraga already added the CONTRIBUTING.md file so that one is closed

**Comment by Nitish18** [comment]
Hi @raj-subhankar,
the Android version will be almost like the React one. Same functionality will be there. I am planning to use GitHub Developers API's for achieving them.

**Comment by raj-subhankar** [comment]
@Nitish18 cool

**Comment by daordonez11** [comment]
Im planning to do some code for hacktoberfest, if you need help on android create an Issue and I'll be happy to help
